--------------------------------------------------------
--  DDL for Table ADRESA
--------------------------------------------------------

  CREATE TABLE "OLTP"."ADRESA"
   (	"ID_ADRESA" NUMBER(10,0),
	"COD_POSTAL" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"STRADA" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"ID_ORAS" NUMBER(10,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0036541
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."SYS_C0036541" ON "OLTP"."ADRESA" ("ID_ADRESA")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table ADRESA
--------------------------------------------------------

  ALTER TABLE "OLTP"."ADRESA" MODIFY ("ID_ADRESA" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."ADRESA" MODIFY ("STRADA" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."ADRESA" ADD PRIMARY KEY ("ID_ADRESA")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADRESA
--------------------------------------------------------

  ALTER TABLE "OLTP"."ADRESA" ADD CONSTRAINT "FKN4U3O4VPUFLV7UDFEPF1HRDYG" FOREIGN KEY ("ID_ORAS")
	  REFERENCES "OLTP"."ORAS" ("ID_ORAS") ENABLE;

--------------------------------------------------------
--  DDL for Table AEROPORT
--------------------------------------------------------

  CREATE TABLE "OLTP"."AEROPORT"
   (	"ID_AEROPORT" NUMBER(10,0),
	"AN_CONSTRUCTIE" NUMBER(10,0),
	"CAPACITATE" NUMBER(10,0),
	"DENUMIRE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"ID_ADRESA" NUMBER(10,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0036544
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."SYS_C0036544" ON "OLTP"."AEROPORT" ("ID_AEROPORT")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index UK_JBJ7CITGK5RA2CF303B33EN9W
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."UK_JBJ7CITGK5RA2CF303B33EN9W" ON "OLTP"."AEROPORT" ("DENUMIRE")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table AEROPORT
--------------------------------------------------------

  ALTER TABLE "OLTP"."AEROPORT" ADD CONSTRAINT "UK_JBJ7CITGK5RA2CF303B33EN9W" UNIQUE ("DENUMIRE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "OLTP"."AEROPORT" MODIFY ("ID_AEROPORT" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."AEROPORT" MODIFY ("DENUMIRE" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."AEROPORT" ADD PRIMARY KEY ("ID_AEROPORT")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AEROPORT
--------------------------------------------------------

  ALTER TABLE "OLTP"."AEROPORT" ADD CONSTRAINT "FKPVAXMB2MJGLJLW38SYR3T271K" FOREIGN KEY ("ID_ADRESA")
	  REFERENCES "OLTP"."ADRESA" ("ID_ADRESA") ENABLE;

--------------------------------------------------------
--  DDL for Table AVION
--------------------------------------------------------

  CREATE TABLE "OLTP"."AVION"
   (	"ID_AVION" NUMBER(10,0),
	"AN_CONSTRUCTIE" NUMBER(5,0),
	"CAPACITATE" NUMBER(10,0),
	"DENUMIRE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"ID_COMPANIE_AERIANA" NUMBER(10,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0036548
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."SYS_C0036548" ON "OLTP"."AVION" ("ID_AVION")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table AVION
--------------------------------------------------------

  ALTER TABLE "OLTP"."AVION" MODIFY ("ID_AVION" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."AVION" MODIFY ("CAPACITATE" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."AVION" MODIFY ("DENUMIRE" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."AVION" ADD PRIMARY KEY ("ID_AVION")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AVION
--------------------------------------------------------

  ALTER TABLE "OLTP"."AVION" ADD CONSTRAINT "FKRNXLFYNU5JEYDTNOD4MH48EU1" FOREIGN KEY ("ID_COMPANIE_AERIANA")
	  REFERENCES "OLTP"."COMPANIE_AERIANA" ("ID_COMPANIE_AERIANA") ENABLE;

--------------------------------------------------------
--  DDL for Table AVION
--------------------------------------------------------

  CREATE TABLE "OLTP"."AVION"
   (	"ID_AVION" NUMBER(10,0),
	"AN_CONSTRUCTIE" NUMBER(5,0),
	"CAPACITATE" NUMBER(10,0),
	"DENUMIRE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"ID_COMPANIE_AERIANA" NUMBER(10,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0036548
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."SYS_C0036548" ON "OLTP"."AVION" ("ID_AVION")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table AVION
--------------------------------------------------------

  ALTER TABLE "OLTP"."AVION" MODIFY ("ID_AVION" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."AVION" MODIFY ("CAPACITATE" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."AVION" MODIFY ("DENUMIRE" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."AVION" ADD PRIMARY KEY ("ID_AVION")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AVION
--------------------------------------------------------

  ALTER TABLE "OLTP"."AVION" ADD CONSTRAINT "FKRNXLFYNU5JEYDTNOD4MH48EU1" FOREIGN KEY ("ID_COMPANIE_AERIANA")
	  REFERENCES "OLTP"."COMPANIE_AERIANA" ("ID_COMPANIE_AERIANA") ENABLE;

--------------------------------------------------------
--  DDL for Table BILET
--------------------------------------------------------

  CREATE TABLE "OLTP"."BILET"
   (	"ID_CLIENT" NUMBER(10,0),
	"ID_ZBOR" NUMBER(10,0),
	"DATA_ACHIZITIONARE" DATE,
	"PRET" FLOAT(126),
	"ID_TIP_BILET" NUMBER(10,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0036553
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."SYS_C0036553" ON "OLTP"."BILET" ("ID_CLIENT", "ID_ZBOR")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table BILET
--------------------------------------------------------

  ALTER TABLE "OLTP"."BILET" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."BILET" MODIFY ("ID_ZBOR" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."BILET" MODIFY ("DATA_ACHIZITIONARE" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."BILET" MODIFY ("PRET" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."BILET" ADD PRIMARY KEY ("ID_CLIENT", "ID_ZBOR")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BILET
--------------------------------------------------------

  ALTER TABLE "OLTP"."BILET" ADD CONSTRAINT "FK5D9YRPMHMSQWO98W7KLRTHDAO" FOREIGN KEY ("ID_TIP_BILET")
	  REFERENCES "OLTP"."TIP_BILET" ("ID_TIP_BILET") ENABLE;

--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "OLTP"."CLIENT"
   (	"ID_CLIENT" NUMBER(10,0),
	"DATA_NASTERII" DATE,
	"NUME" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"PRENUME" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"ID_CONTACT" NUMBER(10,0),
	"CNP" VARCHAR2(13 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index UK_CLIENT_CONTACT
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."UK_CLIENT_CONTACT" ON "OLTP"."CLIENT" ("ID_CONTACT")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0036557
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."SYS_C0036557" ON "OLTP"."CLIENT" ("ID_CLIENT")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "OLTP"."CLIENT" ADD CONSTRAINT "UK_CLIENT_CONTACT" UNIQUE ("ID_CONTACT")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "OLTP"."CLIENT" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."CLIENT" MODIFY ("NUME" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."CLIENT" MODIFY ("PRENUME" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."CLIENT" ADD PRIMARY KEY ("ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "OLTP"."CLIENT" ADD CONSTRAINT "FKT6KR8523JPMIUJ1BBHTIC7Y36" FOREIGN KEY ("ID_CONTACT")
	  REFERENCES "OLTP"."CONTACT" ("ID_CONTACT") ENABLE;

--------------------------------------------------------
--  DDL for Table COMPANIE_AERIANA
--------------------------------------------------------

  CREATE TABLE "OLTP"."COMPANIE_AERIANA"
   (	"ID_COMPANIE_AERIANA" NUMBER(10,0),
	"ANUL_INFIINTARII" NUMBER(5,0),
	"DENUMIRE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"ID_CONTACT" NUMBER(10,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index UK_COMPANIE_AERIANA_CONTACT
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."UK_COMPANIE_AERIANA_CONTACT" ON "OLTP"."COMPANIE_AERIANA" ("ID_CONTACT")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0036560
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."SYS_C0036560" ON "OLTP"."COMPANIE_AERIANA" ("ID_COMPANIE_AERIANA")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index UK_O21UG8TVMHBQ1K5VWPI3H2A4J
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."UK_O21UG8TVMHBQ1K5VWPI3H2A4J" ON "OLTP"."COMPANIE_AERIANA" ("DENUMIRE")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table COMPANIE_AERIANA
--------------------------------------------------------

  ALTER TABLE "OLTP"."COMPANIE_AERIANA" ADD CONSTRAINT "UK_O21UG8TVMHBQ1K5VWPI3H2A4J" UNIQUE ("DENUMIRE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "OLTP"."COMPANIE_AERIANA" ADD CONSTRAINT "UK_COMPANIE_AERIANA_CONTACT" UNIQUE ("ID_CONTACT")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "OLTP"."COMPANIE_AERIANA" MODIFY ("ID_COMPANIE_AERIANA" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."COMPANIE_AERIANA" MODIFY ("DENUMIRE" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."COMPANIE_AERIANA" ADD PRIMARY KEY ("ID_COMPANIE_AERIANA")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMPANIE_AERIANA
--------------------------------------------------------

  ALTER TABLE "OLTP"."COMPANIE_AERIANA" ADD CONSTRAINT "FKOJQFBMHT5ERP70K1OQL6AG0Q8" FOREIGN KEY ("ID_CONTACT")
	  REFERENCES "OLTP"."CONTACT" ("ID_CONTACT") ENABLE;

--------------------------------------------------------
--  DDL for Table CONTACT
--------------------------------------------------------

  CREATE TABLE "OLTP"."CONTACT"
   (	"ID_CONTACT" NUMBER(10,0),
	"EMAIL" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"TELEFON" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"WEBSITE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0036563
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."SYS_C0036563" ON "OLTP"."CONTACT" ("ID_CONTACT")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index UK_Q28WRUVW4JSHP1XWANUYBJSKM
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."UK_Q28WRUVW4JSHP1XWANUYBJSKM" ON "OLTP"."CONTACT" ("EMAIL")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table CONTACT
--------------------------------------------------------

  ALTER TABLE "OLTP"."CONTACT" ADD CONSTRAINT "UK_Q28WRUVW4JSHP1XWANUYBJSKM" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "OLTP"."CONTACT" MODIFY ("ID_CONTACT" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."CONTACT" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."CONTACT" ADD PRIMARY KEY ("ID_CONTACT")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;

--------------------------------------------------------
--  DDL for Table JUDET
--------------------------------------------------------

  CREATE TABLE "OLTP"."JUDET"
   (	"ID_JUDET" NUMBER(10,0),
	"ABREVIERE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"DENUMIRE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"ID_TARA" NUMBER(10,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0036566
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."SYS_C0036566" ON "OLTP"."JUDET" ("ID_JUDET")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index UK_425JJKXMPFGQE5C9WKP1D5IJT
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."UK_425JJKXMPFGQE5C9WKP1D5IJT" ON "OLTP"."JUDET" ("DENUMIRE")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table JUDET
--------------------------------------------------------

  ALTER TABLE "OLTP"."JUDET" ADD CONSTRAINT "UK_425JJKXMPFGQE5C9WKP1D5IJT" UNIQUE ("DENUMIRE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "OLTP"."JUDET" MODIFY ("ID_JUDET" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."JUDET" MODIFY ("DENUMIRE" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."JUDET" ADD PRIMARY KEY ("ID_JUDET")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JUDET
--------------------------------------------------------

  ALTER TABLE "OLTP"."JUDET" ADD CONSTRAINT "FKFW63L24XV4US67BF5IGJGMIY8" FOREIGN KEY ("ID_TARA")
	  REFERENCES "OLTP"."TARA" ("ID_TARA") ENABLE;

--------------------------------------------------------
--  DDL for Table ORAS
--------------------------------------------------------

  CREATE TABLE "OLTP"."ORAS"
   (	"ID_ORAS" NUMBER(10,0),
	"ABREVIERE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"DENUMIRE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"ID_JUDET" NUMBER(10,0),
	"ID_ZONA_COVID" NUMBER(10,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0036569
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."SYS_C0036569" ON "OLTP"."ORAS" ("ID_ORAS")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table ORAS
--------------------------------------------------------

  ALTER TABLE "OLTP"."ORAS" MODIFY ("ID_ORAS" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."ORAS" MODIFY ("DENUMIRE" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."ORAS" ADD PRIMARY KEY ("ID_ORAS")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORAS
--------------------------------------------------------

  ALTER TABLE "OLTP"."ORAS" ADD CONSTRAINT "FKADNUNC1989PIABFQKVQQTJN5P" FOREIGN KEY ("ID_JUDET")
	  REFERENCES "OLTP"."JUDET" ("ID_JUDET") ENABLE;
  ALTER TABLE "OLTP"."ORAS" ADD CONSTRAINT "FKQYVQQ5GB2X2XP5XLA5XIF0CY6" FOREIGN KEY ("ID_ZONA_COVID")
	  REFERENCES "OLTP"."ZONA_COVID" ("ID_ZONA_COVID") ENABLE;

--------------------------------------------------------
--  DDL for Table PILOT
--------------------------------------------------------

  CREATE TABLE "OLTP"."PILOT"
   (	"ID_PILOT" NUMBER(10,0),
	"DATA_ANGAJARII" DATE,
	"DATA_NASTERII" DATE,
	"NUME" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"PRENUME" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"ID_COMPANIE_AERIANA" NUMBER(10,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0036574
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."SYS_C0036574" ON "OLTP"."PILOT" ("ID_PILOT")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table PILOT
--------------------------------------------------------

  ALTER TABLE "OLTP"."PILOT" MODIFY ("ID_PILOT" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."PILOT" MODIFY ("DATA_NASTERII" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."PILOT" MODIFY ("NUME" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."PILOT" MODIFY ("PRENUME" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."PILOT" ADD PRIMARY KEY ("ID_PILOT")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PILOT
--------------------------------------------------------

  ALTER TABLE "OLTP"."PILOT" ADD CONSTRAINT "FKS75PMSDUOFM8YYJ3W6WXK9R2T" FOREIGN KEY ("ID_COMPANIE_AERIANA")
	  REFERENCES "OLTP"."COMPANIE_AERIANA" ("ID_COMPANIE_AERIANA") ENABLE;

--------------------------------------------------------
--  DDL for Table TARA
--------------------------------------------------------

  CREATE TABLE "OLTP"."TARA"
   (	"ID_TARA" NUMBER(10,0),
	"ABREVIERE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"DENUMIRE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0036577
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."SYS_C0036577" ON "OLTP"."TARA" ("ID_TARA")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index UK_2EA9BAGXOUHT35QSM5CUTW6KM
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."UK_2EA9BAGXOUHT35QSM5CUTW6KM" ON "OLTP"."TARA" ("DENUMIRE")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TARA
--------------------------------------------------------

  ALTER TABLE "OLTP"."TARA" ADD CONSTRAINT "UK_2EA9BAGXOUHT35QSM5CUTW6KM" UNIQUE ("DENUMIRE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "OLTP"."TARA" MODIFY ("ID_TARA" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."TARA" MODIFY ("DENUMIRE" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."TARA" ADD PRIMARY KEY ("ID_TARA")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;

--------------------------------------------------------
--  DDL for Table TIP_BILET
--------------------------------------------------------

  CREATE TABLE "OLTP"."TIP_BILET"
   (	"ID_TIP_BILET" NUMBER(10,0),
	"DENUMIRE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"DESCRIERE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0036580
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."SYS_C0036580" ON "OLTP"."TIP_BILET" ("ID_TIP_BILET")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index UK_8820UCGSWNJJFXN4IREQ99045
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."UK_8820UCGSWNJJFXN4IREQ99045" ON "OLTP"."TIP_BILET" ("DENUMIRE")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TIP_BILET
--------------------------------------------------------

  ALTER TABLE "OLTP"."TIP_BILET" ADD CONSTRAINT "UK_8820UCGSWNJJFXN4IREQ99045" UNIQUE ("DENUMIRE")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "OLTP"."TIP_BILET" MODIFY ("ID_TIP_BILET" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."TIP_BILET" MODIFY ("DENUMIRE" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."TIP_BILET" ADD PRIMARY KEY ("ID_TIP_BILET")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;

--------------------------------------------------------
--  DDL for Table ZBOR
--------------------------------------------------------

  CREATE TABLE "OLTP"."ZBOR"
   (	"ID_ZBOR" NUMBER(10,0),
	"DATA_PLECARE_ESTIMATA" TIMESTAMP (6),
	"DATA_PLECARE_REALA" TIMESTAMP (6),
	"DATA_SOSIRE_ESTIMATA" TIMESTAMP (6),
	"DATA_SOSIRE_REALA" TIMESTAMP (6),
	"ID_AEROPORT_PLECARE" NUMBER(10,0),
	"ID_AEROPORT_SOSIRE" NUMBER(10,0),
	"ID_AVION" NUMBER(10,0),
	"ID_COMPANIE_AERIANA" NUMBER(10,0),
	"ID_COPILOT" NUMBER(10,0),
	"ID_PILOT" NUMBER(10,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0036584
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."SYS_C0036584" ON "OLTP"."ZBOR" ("ID_ZBOR")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table ZBOR
--------------------------------------------------------

  ALTER TABLE "OLTP"."ZBOR" MODIFY ("ID_ZBOR" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."ZBOR" MODIFY ("DATA_PLECARE_ESTIMATA" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."ZBOR" MODIFY ("DATA_SOSIRE_ESTIMATA" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."ZBOR" ADD PRIMARY KEY ("ID_ZBOR")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ZBOR
--------------------------------------------------------

  ALTER TABLE "OLTP"."ZBOR" ADD CONSTRAINT "FK1J4EFGWM1N54PYGCO1WV7OBAH" FOREIGN KEY ("ID_AEROPORT_PLECARE")
	  REFERENCES "OLTP"."AEROPORT" ("ID_AEROPORT") ENABLE;
  ALTER TABLE "OLTP"."ZBOR" ADD CONSTRAINT "FKITXAUAV8URNT7U6Q340T4GBEC" FOREIGN KEY ("ID_AEROPORT_SOSIRE")
	  REFERENCES "OLTP"."AEROPORT" ("ID_AEROPORT") ENABLE;
  ALTER TABLE "OLTP"."ZBOR" ADD CONSTRAINT "FKTRM2QKK9SWND9JELK15HTUY70" FOREIGN KEY ("ID_AVION")
	  REFERENCES "OLTP"."AVION" ("ID_AVION") ENABLE;
  ALTER TABLE "OLTP"."ZBOR" ADD CONSTRAINT "FKG8HDQNTA0PFRRCP5RS2BQ09L4" FOREIGN KEY ("ID_COMPANIE_AERIANA")
	  REFERENCES "OLTP"."COMPANIE_AERIANA" ("ID_COMPANIE_AERIANA") ENABLE;
  ALTER TABLE "OLTP"."ZBOR" ADD CONSTRAINT "FKSC1MBYFTKEF4SS0ORPCO2FNUT" FOREIGN KEY ("ID_COPILOT")
	  REFERENCES "OLTP"."PILOT" ("ID_PILOT") ENABLE;
  ALTER TABLE "OLTP"."ZBOR" ADD CONSTRAINT "FKSX6GBINJOCM3Q531MXLWVNCMS" FOREIGN KEY ("ID_PILOT")
	  REFERENCES "OLTP"."PILOT" ("ID_PILOT") ENABLE;










--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "OLTP"."USERS"
   (	"ID" NUMBER(10,0),
	"ACCOUNTNOTEXPIRED" NUMBER(1,0),
	"ACCOUNTNOTLOCKED" NUMBER(1,0),
	"CREDENTIALSNOTEXPIRED" NUMBER(1,0),
	"ENABLED" NUMBER(1,0),
	"PASSWORD" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP",
	"USERNAME" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0036151
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."SYS_C0036151" ON "OLTP"."USERS" ("ID")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "OLTP"."USERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."USERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;

--------------------------------------------------------
--  DDL for Table AUTHORITY
--------------------------------------------------------

  CREATE TABLE "OLTP"."AUTHORITY"
   (	"ID" NUMBER(10,0),
	"ROLE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0036124
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."SYS_C0036124" ON "OLTP"."AUTHORITY" ("ID")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table AUTHORITY
--------------------------------------------------------

  ALTER TABLE "OLTP"."AUTHORITY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."AUTHORITY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;

--------------------------------------------------------
--  DDL for Table AUTHORITY
--------------------------------------------------------

  CREATE TABLE "OLTP"."AUTHORITY"
   (	"ID" NUMBER(10,0),
	"ROLE" VARCHAR2(255 CHAR) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C0036124
--------------------------------------------------------

  CREATE UNIQUE INDEX "OLTP"."SYS_C0036124" ON "OLTP"."AUTHORITY" ("ID")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table AUTHORITY
--------------------------------------------------------

  ALTER TABLE "OLTP"."AUTHORITY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "OLTP"."AUTHORITY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
