ALTER TABLE DW.TIP_BILET ADD CONSTRAINT UK_TIP_BILET_DENUMIRE UNIQUE (DENUMIRE);
ALTER TABLE DW.TIP_BILET MODIFY DENUMIRE NOT NULL;

ALTER TABLE DW.AEROPORT ADD CONSTRAINT UK_AEROPORT_DENUMIRE UNIQUE (DENUMIRE) DISABLE VALIDATE;
ALTER TABLE DW.AEROPORT MODIFY DENUMIRE NOT NULL;
ALTER TABLE DW.AEROPORT MODIFY TARA NOT NULL;
ALTER TABLE DW.AEROPORT MODIFY JUDET NOT NULL;
ALTER TABLE DW.AEROPORT MODIFY ORAS NOT NULL;
ALTER TABLE DW.AEROPORT MODIFY STRADA NOT NULL;

ALTER TABLE DW.CLIENT MODIFY PRENUME NOT NULL;
ALTER TABLE DW.CLIENT MODIFY NUME NOT NULL;
ALTER TABLE DW.CLIENT ADD CONSTRAINT UK_CLIENT_CNP UNIQUE (CNP) DISABLE VALIDATE;
ALTER TABLE DW.CLIENT MODIFY EMAIL NOT NULL;
ALTER TABLE DW.CLIENT ADD CONSTRAINT UK_CLIENT_EMAIL UNIQUE (EMAIL) DISABLE VALIDATE;

ALTER TABLE DW.COMPANIE_AERIANA ADD CONSTRAINT UK_COMPANIE_AERIANA_DENUMIRE UNIQUE (DENUMIRE) DISABLE VALIDATE;
ALTER TABLE DW.COMPANIE_AERIANA MODIFY DENUMIRE NOT NULL;
ALTER TABLE DW.COMPANIE_AERIANA ADD CONSTRAINT UK_COMPANIE_AERIANA_EMAIL UNIQUE (EMAIL) DISABLE VALIDATE;
ALTER TABLE DW.COMPANIE_AERIANA MODIFY EMAIL NOT NULL;

ALTER TABLE DW.PILOT MODIFY PRENUME NOT NULL;
ALTER TABLE DW.PILOT MODIFY NUME NOT NULL;
ALTER TABLE DW.PILOT MODIFY VARSTA NOT NULL;

ALTER TABLE DW.AVION MODIFY DENUMIRE NOT NULL;
ALTER TABLE DW.AVION MODIFY CAPACITATE NOT NULL;

