ALTER SYSTEM SET OPTIMIZER_IGNORE_HINTS=FALSE;

--1 BITMAP INDEX
--DROP INDEX ZONA_COVID_IDX;
CREATE BITMAP INDEX ZONA_COVID_IDX
ON DW.AEROPORT(ZONA_COVID);

-- compare execution plans
-- INDEX unused
ANALYZE TABLE DW.AEROPORT COMPUTE STATISTICS;

ALTER INDEX ZONA_COVID_IDX UNUSABLE;

EXPLAIN PLAN FOR
--aeroporturile din zona Rosie din care au decolat cele mai multe zboruri
SELECT 
     A.DENUMIRE AEROPORT
    ,COUNT(*) NR_PLECARI
FROM DW.AEROPORT A
JOIN DW.ZBOR Z ON A.ID_AEROPORT = Z.ID_AEROPORT_PLECARE
WHERE ZONA_COVID = 'Rosu'
GROUP BY A.DENUMIRE
ORDER BY 2 DESC;

SELECT PLAN_TABLE_OUTPUT 
FROM TABLE(DBMS_XPLAN.DISPLAY()); 



-- INDEX used
ALTER INDEX ZONA_COVID_IDX REBUILD;

ANALYZE TABLE DW.AEROPORT COMPUTE STATISTICS;
ANALYZE INDEX ZONA_COVID_IDX COMPUTE STATISTICS;

EXPLAIN PLAN 
FOR
--aeroporturile din zona Rosie din care au decolat cele mai multe zboruri
SELECT /*+INDEX(A ZONA_COVID_IDX) */
     A.DENUMIRE AEROPORT
    ,COUNT(*) NR_PLECARI
FROM DW.AEROPORT A
JOIN DW.ZBOR Z ON A.ID_AEROPORT = Z.ID_AEROPORT_PLECARE
WHERE ZONA_COVID = 'Rosu'
GROUP BY A.DENUMIRE
ORDER BY 2 DESC;

SELECT PLAN_TABLE_OUTPUT 
FROM TABLE(DBMS_XPLAN.DISPLAY()); 






--2 BITMAP JOIN INDEX
--DROP INDEX TIP_BILET_IDX;
CREATE BITMAP INDEX TIP_BILET_IDX
ON DW.BILET(DW.TIP_BILET.DENUMIRE)
FROM DW.BILET, DW.TIP_BILET
WHERE DW.BILET.ID_TIP_BILET = DW.TIP_BILET.ID_TIP_BILET
LOCAL;


-- compare execution plans
-- INDEX unused
ANALYZE TABLE DW.BILET COMPUTE STATISTICS;
ANALYZE TABLE DW.TIP_BILET COMPUTE STATISTICS;

ALTER INDEX TIP_BILET_IDX UNUSABLE;

EXPLAIN PLAN FOR 
SELECT 
    AVG(B.PRET) AS AVG_PRET
FROM DW.BILET B
JOIN DW.TIP_BILET TB ON B.ID_TIP_BILET = TB.ID_TIP_BILET
WHERE TB.DENUMIRE = 'First class';

SELECT PLAN_TABLE_OUTPUT 
FROM TABLE(DBMS_XPLAN.DISPLAY()); 



-- INDEX used
ALTER INDEX TIP_BILET_IDX REBUILD;
ANALYZE INDEX TIP_BILET_IDX COMPUTE STATISTICS;
EXPLAIN PLAN 
FOR 
SELECT /*+INDEX(B TIP_BILET_IDX) */
    AVG(B.PRET) AS AVG_PRET
FROM DW.BILET B
JOIN DW.TIP_BILET TB ON B.ID_TIP_BILET = TB.ID_TIP_BILET
WHERE TB.DENUMIRE = 'First class';

SELECT PLAN_TABLE_OUTPUT 
FROM TABLE(DBMS_XPLAN.DISPLAY()); 

