--DROP UNIQUE CONSTRAINT
ALTER TABLE DW.AEROPORT DROP CONSTRAINT UK_AEROPORT_DENUMIRE;

INSERT INTO DW.AEROPORT(
     ID_AEROPORT
    ,DENUMIRE
    ,CAPACITATE
    ,AN_CONSTRUCTIE
    ,TARA
    ,JUDET
    ,ORAS
    ,STRADA
    ,COD_POSTAL
    ,ZONA_COVID
)
SELECT
     AE.ID_AEROPORT
    ,AE.DENUMIRE
    ,AE.CAPACITATE
    ,AE.AN_CONSTRUCTIE
    ,T.DENUMIRE AS TARA
    ,J.DENUMIRE AS JUDET
    ,O.DENUMIRE AS ORAS
    ,AD.STRADA
    ,AD.COD_POSTAL
    ,ZC.ZONA
FROM OLTP.AEROPORT AE
JOIN OLTP.ADRESA AD ON AE.ID_ADRESA = AD.ID_ADRESA
JOIN OLTP.ORAS O ON AD.ID_ORAS = O.ID_ORAS
JOIN OLTP.JUDET J ON O.ID_JUDET = J.ID_JUDET
JOIN OLTP.TARA T ON J.ID_TARA = T.ID_TARA
JOIN OLTP.ZONA_COVID ZC ON O.ID_ZONA_COVID = ZC.ID_ZONA_COVID
WHERE AE.DENUMIRE NOT IN (SELECT DENUMIRE FROM DW.AEROPORT);

--recreate UNIQUE CONSTRAINT
ALTER TABLE DW.AEROPORT ADD CONSTRAINT UK_AEROPORT_DENUMIRE UNIQUE (DENUMIRE) DISABLE VALIDATE;


--DROP UNIQUE CONSTRAINT
ALTER TABLE DW.COMPANIE_AERIANA DROP CONSTRAINT UK_COMPANIE_AERIANA_DENUMIRE;
ALTER TABLE DW.COMPANIE_AERIANA DROP CONSTRAINT UK_COMPANIE_AERIANA_EMAIL;

INSERT INTO DW.COMPANIE_AERIANA(
     ID_COMPANIE_AERIANA
    ,DENUMIRE
    ,VECHIME
    ,EMAIL
    ,TELEFON
    ,WEBSITE
)
SELECT
     CA.ID_COMPANIE_AERIANA
    ,CA.DENUMIRE
    ,EXTRACT(YEAR FROM SYSDATE) - CA.ANUL_INFIINTARII AS VECHIME
    ,CO.EMAIL
    ,CO.TELEFON
    ,CO.WEBSITE
FROM OLTP.COMPANIE_AERIANA CA
JOIN OLTP.CONTACT CO ON CA.ID_CONTACT = CO.ID_CONTACT
WHERE
    CA.DENUMIRE NOT IN (SELECT DENUMIRE FROM DW.COMPANIE_AERIANA) AND 
    CO.EMAIL NOT IN (SELECT EMAIL FROM DW.COMPANIE_AERIANA);

--recreate UNIQUE CONSTRAINT
ALTER TABLE DW.COMPANIE_AERIANA ADD CONSTRAINT UK_COMPANIE_AERIANA_DENUMIRE UNIQUE (DENUMIRE) DISABLE VALIDATE;
ALTER TABLE DW.COMPANIE_AERIANA ADD CONSTRAINT UK_COMPANIE_AERIANA_EMAIL UNIQUE (EMAIL) DISABLE VALIDATE;


INSERT INTO DW.AVION(
     ID_AVION
    ,DENUMIRE
    ,CAPACITATE
    ,AN_CONSTRUCTIE
    ,ID_COMPANIE_AERIANA
)
SELECT
     ID_AVION
    ,DENUMIRE
    ,CAPACITATE
    ,AN_CONSTRUCTIE
    ,ID_COMPANIE_AERIANA
FROM OLTP.AVION;


INSERT INTO DW.BILET(
     ID_ZBOR
    ,ID_CLIENT
    ,PRET
    ,ID_DATA_ACHIZITIONARII
    ,ID_TIP_BILET
)
SELECT
     B.ID_ZBOR
    ,B.ID_CLIENT
    ,B.PRET
    ,T.ID_TIMP
    ,B.ID_TIP_BILET
FROM OLTP.BILET B
JOIN DW.TIMP T ON 
    EXTRACT(YEAR FROM B.DATA_ACHIZITIONARE) = T.AN AND
    EXTRACT(MONTH FROM B.DATA_ACHIZITIONARE) = T.LUNA AND
    EXTRACT(DAY FROM B.DATA_ACHIZITIONARE) = T.ZI AND
    TO_CHAR(B.DATA_ACHIZITIONARE, 'HH24') = T.ORA;
    
    
--DROP UNIQUE CONSTRAINT
ALTER TABLE DW.CLIENT DROP CONSTRAINT UK_CLIENT_EMAIL;
ALTER TABLE DW.CLIENT DROP CONSTRAINT UK_CLIENT_CNP;

INSERT INTO DW.CLIENT(
     ID_CLIENT
    ,PRENUME
    ,NUME
    ,CNP
    ,VARSTA
    ,EMAIL
    ,TELEFON
)
SELECT
     CL.ID_CLIENT
    ,CL.PRENUME
    ,CL.NUME
    ,'?' AS CNP
    ,TRUNC(TO_NUMBER(SYSDATE - CL.DATA_NASTERII) / 365.25) AS VARSTA --possible to move to generated column approach?
    ,CO.EMAIL
    ,CO.TELEFON
FROM OLTP.CLIENT CL
JOIN OLTP.CONTACT CO ON CL.ID_CONTACT = CO.ID_CONTACT
WHERE CO.EMAIL NOT IN (SELECT EMAIL FROM DW.CLIENT);

--recreate UNIQUE CONSTRAINT
ALTER TABLE DW.CLIENT ADD CONSTRAINT UK_CLIENT_EMAIL UNIQUE (EMAIL) DISABLE VALIDATE;
ALTER TABLE DW.CLIENT ADD CONSTRAINT UK_CLIENT_CNP UNIQUE (CNP) DISABLE VALIDATE;


INSERT INTO DW.PILOT(
     ID_PILOT
    ,PRENUME
    ,NUME
    ,VARSTA
    ,EXPERIENTA
    ,ID_COMPANIE_AERIANA
)
SELECT
     ID_PILOT
    ,PRENUME
    ,NUME
    ,TRUNC(TO_NUMBER(SYSDATE - DATA_NASTERII) / 365.25) AS VARSTA
    ,TRUNC(TO_NUMBER(SYSDATE - DATA_ANGAJARII) / 365.25) AS EXPERIENTA
    ,ID_COMPANIE_AERIANA
FROM OLTP.PILOT;


INSERT INTO DW.TIP_BILET(
    ID_TIP_BILET,
    DENUMIRE,
    DESCRIERE
)
SELECT     ID_TIP_BILET,
           DENUMIRE,
           DESCRIERE
FROM OLTP.TIP_BILET;


--TIP BILET TREBUIE SA FIE IN TABELUL BILET




INSERT INTO DW.ZBOR(
     ID_ZBOR
    ,DURATA_ZBOR
    ,INTARZIERE
    ,ID_AVION
    ,ID_PILOT
    ,ID_COPILOT
    ,ID_AEROPORT_PLECARE
    ,ID_AEROPORT_SOSIRE
    ,ID_COMPANIE_AERIANA
    ,ID_DATA_PLECARE
    ,ID_DATA_SOSIRE
)
SELECT
     Z.ID_ZBOR
    ,GREATEST(0, EXTRACT(HOUR FROM (Z.DATA_SOSIRE_REALA - Z.DATA_PLECARE_REALA)) * 60 + EXTRACT(MINUTE FROM (Z.DATA_SOSIRE_REALA - Z.DATA_PLECARE_REALA))) AS DURATA_ZBOR
    ,GREATEST(0, EXTRACT(HOUR FROM (Z.DATA_SOSIRE_REALA - Z.DATA_SOSIRE_ESTIMATA)) * 60 + EXTRACT(MINUTE FROM (Z.DATA_SOSIRE_REALA - Z.DATA_SOSIRE_ESTIMATA))) AS INTARZIERE
    ,Z.ID_AVION
    ,Z.ID_PILOT
    ,Z.ID_COPILOT
    ,Z.ID_AEROPORT_PLECARE
    ,Z.ID_AEROPORT_SOSIRE
    ,Z.ID_COMPANIE_AERIANA
    ,TP.ID_TIMP AS ID_DATA_PLECARE
    ,TS.ID_TIMP AS ID_DATA_SOSIRE
FROM OLTP.ZBOR Z
JOIN DW.TIMP TP ON 
    EXTRACT(YEAR FROM Z.DATA_PLECARE_REALA) = TP.AN AND
    EXTRACT(MONTH FROM Z.DATA_PLECARE_REALA) = TP.LUNA AND
    EXTRACT(DAY FROM Z.DATA_PLECARE_REALA) = TP.ZI AND
    TO_CHAR(Z.DATA_PLECARE_REALA, 'HH24') = TP.ORA
JOIN DW.TIMP TS ON 
    EXTRACT(YEAR FROM Z.DATA_SOSIRE_REALA) = TS.AN AND
    EXTRACT(MONTH FROM Z.DATA_SOSIRE_REALA) = TS.LUNA AND
    EXTRACT(DAY FROM Z.DATA_SOSIRE_REALA) = TS.ZI AND
    TO_CHAR(Z.DATA_SOSIRE_REALA, 'HH24') = TS.ORA;
